server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location /assets/ {
        try_files $uri =404;
    }

    location /velog-api {
        resolver 8.8.8.8;
        proxy_pass https://v2.velog.io/graphql;
        proxy_http_version 1.1;
        proxy_set_header Host v2.velog.io;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 20s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
