export const profile = {
  name: 'JANG SEONG JU',
  koreanName: '장성주',
  nickname: 'SungJu',
  roles: ['DevOps', 'Backend', 'Frontend', 'ML'],
  intro: '인프라부터 서비스까지, 직접 만들고 배포하는 개발자입니다.',
  email: '20261112@dsm.hs.kr',
  github: 'https://github.com/sungjujjang',
  blog: 'https://velog.io/@sungjujjang/posts',
  followers: 36,
  following: 57,
  repositories: 40,
  stars: 14,
  achievements: ['Pull Shark', 'Pair Extraordinaire', 'YOLO'],
  solvedac: 'https://solved.ac/dsm20261112',
  youtube: 'https://www.youtube.com/watch?v=UCH9QOF2Czyq-sTCJy2kf2A',
}

export const skills = {
  languages: [
    'Python',
    'C',
    'C++',
    'Java',
    'JavaScript',
    'TypeScript',
    'C#',
    'NASM',
    'YAML',
    'JSON',
  ],
  devops: [
    'Docker',
    'Kubernetes',
    'AWS',
    'GCP',
    'Linux',
    'Nginx',
    'Prometheus',
    'Grafana',
    'Cloudflare',
    'Proxmox',
    'ArgoCD',
    'Helm',
  ],
  backend: [
    'Django',
    'Flask',
    'FastAPI',
    'Spring',
    'Express',
    'MySQL',
    'PostgreSQL',
    'Redis',
    'JPA',
    'SQLite',
  ],
  frontend: [
    'React',
    'Next.js',
    'Vite',
    'Figma',
    'Bootstrap',
    'Tailwind',
    'styled-components',
  ],
  ml: ['PyTorch', 'Matplotlib', 'Pandas'],
  mobile: ['Android', 'Flutter'],
  etc: ['Blender', 'Arduino', 'Raspberry Pi'],
}

export const projects = [
  {
    name: 'Teromox',
    emoji: '🖥️',
    description: '홈서버 기반 VPS 서비스',
    tags: ['Linux', 'Kubernetes', 'Proxmox'],
    github: 'https://github.com/sungjujjang/Teromox',
    highlight: true,
  },
  {
    name: 'Carin',
    emoji: '🚕',
    description: '택시 카풀 매칭 플랫폼',
    tags: ['HTML', 'Frontend', 'Service'],
    github: 'https://github.com/sungjujjang/Carin',
    highlight: true,
  },
  {
    name: 'sungjublog',
    emoji: '📝',
    description: 'Next.js 개인 기술 블로그',
    tags: ['Next.js', 'TypeScript'],
    github: 'https://github.com/sungjujjang/sungjublog',
    link: 'https://velog.io/@sungjujjang/posts',
    highlight: true,
  },
  {
    name: 'examplan',
    emoji: '📅',
    description: '실시간 공유 플래너 · 캘린더',
    tags: ['Java', 'Backend'],
    github: 'https://github.com/sungjujjang/examplan',
  },
  {
    name: 'NofiSender',
    emoji: '🔔',
    description: '휴대폰 알림 웹훅 전송 앱',
    tags: ['Java', 'Android'],
    github: 'https://github.com/sungjujjang/NofiSender',
  },
  {
    name: 'kbosunwe',
    emoji: '⚾',
    description: 'KBO 실시간 순위 집계 서비스',
    tags: ['Python', 'HTML', 'Data'],
    github: 'https://github.com/sungjujjang/kbosunwe',
  },
  {
    name: 'gokaist',
    emoji: '✨',
    description: '실시간 협업 웹 프로젝트',
    tags: ['JavaScript'],
    github: 'https://github.com/sungjujjang/gokaist',
  },
  {
    name: 'fastapi_user',
    emoji: '🔐',
    description: 'FastAPI 로그인 베이스 코드',
    tags: ['FastAPI', 'Python'],
    github: 'https://github.com/sungjujjang/fastapi_user',
  },
  {
    name: 'lolnaejeonbot',
    emoji: '🎮',
    description: 'LoL 내전 매치메이킹 봇',
    tags: ['Python', 'Discord Bot'],
    github: 'https://github.com/sungjujjang/lolnaejeonbot',
  },
  {
    name: 'instagramcopybot',
    emoji: '📸',
    description: '인스타 콘텐츠 백업 봇',
    tags: ['Python', 'Automation'],
    github: 'https://github.com/sungjujjang/instagramcopybot',
  },
  {
    name: 'life_excape_game',
    emoji: '🔓',
    description: 'Python 방탈출 게임',
    tags: ['Python', 'Game'],
    github: 'https://github.com/sungjujjang/life_excape_game',
  },
  {
    name: 'yunodiscord',
    emoji: '🃏',
    description: '디스코드 UNO 게임 봇',
    tags: ['Python', 'Discord Bot'],
    github: 'https://github.com/sungjujjang/unodiscord',
  },
  {
    name: 'study',
    emoji: '📚',
    description: '학습 내용을 기록하는 저장소',
    tags: ['Python'],
    github: 'https://github.com/sungjujjang/study',
  },
  {
    name: 'backjoon',
    emoji: '🧩',
    description: '백준 알고리즘 풀이 기록',
    tags: ['Python', 'Algorithm'],
    github: 'https://github.com/sungjujjang/backjoon',
  },
]

export const timeline = [
  {
    date: '2021',
    title: '대구교육대학교 정보영재원 수료',
    description: '컴퓨터과학의 첫걸음',
    tag: '교육',
    emoji: '🎓',
  },
  {
    date: '2022',
    title: '정보영재원 심화과정 수료',
    description: '알고리즘 · 자료구조 심화 학습',
    tag: '교육',
    emoji: '🏅',
  },
  {
    date: '2023',
    title: '정보동아리 SASAC 입단',
    description: '동아리 활동 및 프로젝트 시작',
    tag: '활동',
    emoji: '🚀',
  },
  {
    date: '2023',
    title: 'SW-AI융합 해커톤 참여',
    description: 'AI 모델 설계 · 협업 개발',
    tag: '대회',
    emoji: '🤖',
  },
  {
    date: '2024',
    title: '메타버스 빅데이터 캠프',
    description: '우수 보고서 선정',
    tag: '수상',
    emoji: '📊',
  },
  {
    date: '2025',
    title: '대구창의융합교육원 해커톤 우승',
    description: '문제 해결 프로젝트 개발',
    tag: '수상',
    emoji: '🏆',
  },
  {
    date: '2025',
    title: '달빛연합 SW융합 해커톤',
    description: '최우수상 · 인기상 · 창의상 수상',
    tag: '수상',
    emoji: '👑',
  },
  {
    date: '2026',
    title: '대덕소프트웨어마이스터고 입학',
    description: '전공동아리 XQUARE — DevOps · Backend · Frontend',
    tag: '학교',
    emoji: '💻',
  },
  {
    date: '2026',
    title: '교내 해커톤 우수상',
    description: '대덕소프트웨어마이스터고 주최',
    tag: '학교',
    emoji: '👑',
  },
  {
    date: '2026',
    title: '카카오 AI 루키캠프 수료',
    description: 'AI/ML 실무형 프로젝트 경험',
    tag: '교육',
    emoji: '🤖',
  },
]

export const techGroups = [
  { label: 'DevOps', items: skills.devops, color: '#F54900' },
  { label: 'Backend', items: skills.backend, color: '#38BDF8' },
  { label: 'Frontend', items: skills.frontend, color: '#818CF8' },
  { label: 'Mobile', items: skills.mobile, color: '#34D399' },
  { label: 'ML / AI', items: skills.ml, color: '#F472B6' },
]
